In [4]:
import torch
import numpy as np

In [5]:
torch.__version__

'1.7.1'

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
arr.dtype

dtype('int64')

In [8]:
type(arr)

numpy.ndarray

In [9]:
x= torch.from_numpy(arr)

In [10]:
x

tensor([1, 2, 3, 4, 5])

In [11]:
type(x)

torch.Tensor

In [12]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [14]:
arr2d = np.arange(0.0, 12.0)

In [15]:
arr2d = arr2d.reshape(4,3)

In [16]:
x2 = torch.from_numpy(arr2d)

In [17]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [18]:
arr[0]=99

In [19]:
arr

array([99,  2,  3,  4,  5])

In [29]:
x

tensor([99,  2,  3,  4,  5])

In [30]:
my_arr = np.arange(0,10)

In [31]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
my_arr[0]=9999

In [34]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [35]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
new_array =np.array([1,2,3])

In [38]:
torch.tensor(new_array)

tensor([1, 2, 3])

In [39]:
torch.Tensor(1,2,3)

tensor([[[8.4078e-45, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.4013e-45]]])

`torch.FloatTensor` is same as `torch.Tensor`

In [40]:
torch.empty(2,2)

tensor([[ 0., -2.],
        [ 0., -2.]])

In [41]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [42]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [44]:
torch.arange(0,18,2).reshape(3,3)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [46]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [47]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [48]:
my_tensor = torch.tensor([1,2,3])

In [49]:
my_tensor.dtype

torch.int64

In [50]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [51]:
torch.rand(4,3)

tensor([[0.9543, 0.8607, 0.5410],
        [0.5748, 0.5459, 0.3183],
        [0.1803, 0.7907, 0.3356],
        [0.0396, 0.9148, 0.5879]])

In [52]:
torch.randn(4,3)

tensor([[-0.6343, -0.7525, -0.6644],
        [-0.3114,  0.2754, -2.4781],
        [-0.2331, -0.7446,  0.7398],
        [ 1.2368,  0.7050, -1.0821]])

In [54]:
torch.randint(low=0, high=11, size=(5,5))

tensor([[10,  1,  3,  2,  4],
        [ 2,  7,  3,  0,  8],
        [10,  8,  3, 10, 10],
        [ 5,  4, 10, 10,  0],
        [ 6, 10,  4,  9,  2]])

In [55]:
x=torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [56]:
torch.rand_like(x)

tensor([[0.1451, 0.1846, 0.4290, 0.2876, 0.0936],
        [0.6000, 0.3618, 0.1069, 0.6501, 0.3155]])

In [57]:
torch.randn_like(x)

tensor([[-1.3348,  0.6931,  0.7593, -1.1033, -1.9139],
        [-0.0461, -0.5449, -0.1290,  2.0192,  0.1581]])

In [59]:
torch.randint_like(x,low=0,high=11)

tensor([[9., 7., 2., 8., 2.],
        [7., 6., 8., 4., 2.]])

In [61]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [62]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])