# Pytorch Operations

In [1]:
import torch
import numpy as np

### Reshape

In [2]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
x[1,1]

tensor(3)

### Indexing for the column

In [7]:
x[:,1]

tensor([1, 3, 5])

### Slicing for the column

In [5]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

### View vs Reshape

In [8]:
x1 = torch.arange(10)
x1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x1.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x1.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
x1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x2 = torch.arange(10)

In [14]:
x2.shape

torch.Size([10])

In [16]:
x2.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
x2.shape

torch.Size([10])

In [19]:
z = x2.view(2,5)

In [20]:
z[0] = 99

In [21]:
z

tensor([[99, 99, 99, 99, 99],
        [ 5,  6,  7,  8,  9]])

In [22]:
x2

tensor([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [23]:
x2[0]=9999

In [24]:
z

tensor([[9999,   99,   99,   99,   99],
        [   5,    6,    7,    8,    9]])

#### Infer in View

In [26]:
x3 = torch.arange(10)
x3.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])
a+b

tensor([5., 7., 9.])

In [28]:
a.mul(b)

tensor([ 4., 10., 18.])

In [29]:
a.mul_(b)
a

tensor([ 4., 10., 18.])

## Pytorch Operations II

In [31]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [32]:
a*b

tensor([ 4., 10., 18.])

In [33]:
a.dot(b)

tensor(32.)

### Matrix multiplication

In [35]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [36]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [37]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [38]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

Let us calculate manually
```
0*6 + 2*8 + 4*10 = 56
0*7 + 2*9 + 4*11 = 6
1*6 + 3*8 + 5*10 = 80
1*7 + 3*9 + 5*11 = 89
```

In [40]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [42]:
# shorthand for matrix multiplication
a@b

tensor([[56, 62],
        [80, 89]])

### Euclidean norm

In [43]:
x = torch.tensor([2.,3.,4.,5.])

In [44]:
x.norm()

tensor(7.3485)

In [45]:
x.numel()

4